### ISSUE TITLE
Define the order of items any time an array is used in the parsed output.

### ISSUE THREAD

**Issue by Zegnat** [microformats/microformats2-parsing#29]
The JSON specification, as defined in both RFC 8259 and RFC 7159 (the basis of I-JSON, see #23), states:

> An array is an ordered sequence of zero or more values.

The trick here is the word ordered. The two arrays `["red", "blue"]` and `["blue", "red"]` are different in JSON documents because their order is different. From this follows that two microformats parser implementations that generate different arrays from the same input HTML can be said to be incompatible with each other, as they have distinctly different output. (As seen in #22.)

The microformats parsing specification should fix this by specifying what order should be used any time an array is used.

Most of the arrays used should follow document order. When filling the `items` or `children` arrays with microformat structures it is important to keep document order, as consumers may need to find the first occurrence of a specific object. (Example: the [authorship discovery algorithm](https://indieweb.org/authorship#How_to_determine) depends on being able to access the first `h-card` matching specific constraints.)

But some arrays should not follow document order as they are semantically unordered collections. As an example, the following HTML has 2 `div` elements. While the order of their class names is different in the source, this does not matter. Both have an identical *set* of classes:

```html
<div class="alpha beta"></div>
<div class="beta alpha"></div>
```

Because there is no way to have unsorted arrays in JSON, the microformats specification should define an arbitrary sort for these cases.

Using source order here would be a bad idea. This could lead to people interpreting order as being important or something consuming code can rely on when it shouldn’t. (Source order may [potentially be a source of bugs](https://chat.indieweb.org/microformats/2018-03-19/1521486144203000) here.) Thus data [“derived from unordered sets in the source HTML MUST NOT imply any source order”](https://chat.indieweb.org/microformats/2018-03-19/1521495708031100).

The `class` and `rel` attributes in HTML are the only ones microformats parsing depends on that are sets in the source HTML where order does not matter. These are mapped to arrays in `type` and `rels` respectively.

The proposed solution is to:

1. define that whenever items are added to an array during microformats parsing, this matches the source order,
2. **except** for the `type` and `rels` arrays which should be in alphabetical order.

**Comment by Zegnat** [comment]
There is precedent for using alphabetical sorting. The [PHP parser](https://php.microformats.io/) already does this:

```html
<div class="h-entry h-cite h-entry"></div>
```
```json
"type": [
  "h-cite",
  "h-entry",
  "h-entry"
]
```

The [development version of the Python parser](https://kartikprabhu.com/connection/mfparser) has also been updated to use an alphabetical sorting:


```html
<div class="h-entry h-cite h-entry"></div>
```
```json
"type": [
  "h-cite",
  "h-entry"
]
```

**Comment by tantek** [comment]
As I wrote in <http://tantek.com/2018/079/t2> (<https://github.com/microformats/microformats2-parsing/issues/30#issuecomment-374784404>), the 'type' array must not convey any ordering semantics from the source (thus it must enforce an artificial order that does not convey anything, in addition to uniqueness per set requirements). All other uses of arrays in the parsed JSON output (children, property values, rel subarrays) already convey appropriate document order semantics.

(Originally published at: http://tantek.com/2018/079/t3/)

**Comment by kartikprabhu** [comment]
+1 
cc: @tantek

**Comment by Zegnat** [comment]
Spec has been updated so both `type` and `rels` arrays [must be](http://microformats.org/wiki/index.php?title=microformats2-parsing&diff=66722&oldid=66695) [sorted alphabetically](http://microformats.org/wiki/index.php?title=microformats2-parsing&diff=66724&oldid=66723).
