### ISSUE TITLE
Explicitly define MF2 JSON as an array-of-arrays

### ISSUE THREAD

**Issue by skpy** [microformats/microformats2-parsing#34]
While working on a Micropub implementation, and looking at [p3k-micropub](https://github.com/aaronpk/p3k-micropub), I see that the MF2 JSON format is an array of arrays, but this format is not **explicitly** defined anywhere.  

The [Micropub JSON syntax](https://www.w3.org/TR/micropub/#json-syntax) section describes how to create a JSON object for submission to a Micropub server; but nothing in the Micropub spec declares that the Micropub server is required to respond with the same notation.  This sentence is close:

> When creating posts in JSON format, all values MUST be specified as arrays, even if there is only one value, identical to the Microformats 2 JSON format. 

But I was unable to find the lay person's intro to MF2 JSON that explains this for me.

The [microformats wiki examples](http://microformats.org/wiki/microformats2#details_from_examples) does state this:
> Flat sets of optional properties
>    All microformats consist of a root, and a collection of properties. Hierarchical data is represented with nested microformats, typically as property values themselves. Properties are all optional and potentially multivalued (applications needing a singular semantic may use first instance). 

But that's buried inside the examples section, and not exactly the explicit format declaration that a new reader desires to see.

I would like to see a simple, explicit statement that MF2 JSON format is an array or arrays, as stated in the Micropub spec, to reduce ambiguity.

**Comment by gRegorLove** [comment]
@skpy I think the [microformats2 parsing specification](http://microformats.org/wiki/microformats2-parsing) has what you're looking for.

**Comment by Zegnat** [comment]
I think with the parsing specification already making this clear (so this not being a parsing issue) and the addition of [the new microformats2 JSON page](http://microformats.org/wiki/microformats2-json) this issue can be closed?

**Comment by skpy** [comment]
Agreed, this can be closed.  Thanks!
