### ISSUE TITLE
Falsely implied u-url

### ISSUE THREAD

**Issue by sknebel** [microformats/microformats2-parsing#36]
Found via https://www.zylstra.org/blog/2018/07/wrapping-my-head-around-webmentions/: http://diggingthedigital.com//Waar-te-beginnen-met-Webmentions/ has no explicitly marked up `u-url` and all content wrapped in tags except a single `<a href="https://news.indieweb.org/nl" class="u-syndication"></a>` to submit it to IndieNews. Since there is no explicit `url` property, [implied property parsing](http://microformats.org/wiki/microformats2-parsing#parsing_for_implied_properties) triggers, and this situation matches the second rule for implied `url`s:

> else if .h-x>a[href]:only-of-type:not[.h-*], then use that [href] for url

This clearly should not happen.

At first glance, it seems like a rule similar to the recently introduced for `p-name` would be sensible: do not imply URLs if there are other urls marked up? 

In general, I repeat my question from elsewhere: is there documentation for why the implied rules are like they are? They keep causing various amounts of trouble, and I'd love to understand why they are necessary as they are when discussing them. They clearly cover more than the tiny minimal h-cards: what are they intended to cover?

**Comment by gRegorLove** [comment]
Spec was [updated today](http://microformats.org/wiki/index.php?title=microformats2-parsing&diff=66887&oldid=66871) to reflect the previous consensus.

**Comment by sknebel** [comment]
👍 

One question: does it make sense to change the wording to `no explicit u-* properties" to make it clear implied photo and url can both happen? While the implied properties aren't strictly `u-*` properties, this could still lead to confusion?

**Comment by tantek** [comment]
&lt;https://github.com/sknebel&gt; yes that is the interpretation I intended, and thanks for the review and suggestion. I have added "explicit" explicitly :)

[http://microformats.org/wiki/index.php?title=microformats2-parsing&amp;diff=66898&amp;oldid=66890](http://microformats.org/wiki/index.php?title=microformats2-parsing&amp;diff=66898&amp;oldid=66890)

If with that change we have sufficiently resolved this issue 36, go ahead and close it. Thanks!

(Originally published at: http://tantek.com/2018/211/t1/)

**Comment by snarfed** [comment]
We ran into another case of this that's still a bit problematic and confusing, even with the protections added above. Background in https://github.com/snarfed/bridgy-fed/issues/342, example problematic HTML and mf2 here from https://tmichellemoore.com/blog/testing-7-18/ :

```html
<div class="h-entry">
  <p class="e-content">Testing 7.18.1</p>
  <a href="https://fed.brid.gy/"></a>
</div>
```

```json
{
    "type": [
        "h-entry"
    ],
    "properties": {
        "content": [
            {
                "html": "Testing 7.18.1",
                "value": "Testing 7.18.1",
                "lang": "en-US"
            }
        ],
        "url": [
            "https://fed.brid.gy/"
        ]
    },
    "lang": "en-US"
}
```

**Comment by snarfed** [comment]
Yet another one in Bridgy Publish, https://github.com/snarfed/bridgy/issues/1409 . Chat: https://chat.indieweb.org/microformats/2023-02-01#t1675292217052500 . Implied `u-url` is clearly not having a good time in general.
