### ISSUE TITLE
format for polls

### ISSUE THREAD

**Issue by snarfed** [microformats/microformats2-parsing#55]
Placeholder issue for how to represent and handle polls, including questions and responses. [IndieWeb page with more background.](https://indieweb.org/poll) Not many experiments or mf2 attempts in the wild yet, this from @capjamesg is the only recorded one so far: https://jamesg.blog/2022/05/17/coffee-frequency/

**Comment by snarfed** [comment]
https://github.com/snarfed/granary/issues/75

**Comment by sknebel** [comment]
I'm not sure why this would affect the parsing specification?

**Comment by snarfed** [comment]
@sknebel true! It probably wouldn't. Where should we track proposed/requested microformats like this? https://microformats.org/wiki/microformats2#v2_vocabularies , https://indieweb.org/poll / https://indieweb.org/question , ...?
