### ISSUE TITLE
VCP inner-text is undefined

### ISSUE THREAD

**Issue by JKingweb** [microformats/microformats2-parsing#77]
The Value Class Pattern documentation makes repeated reference to getting an element's "inner-text". This is not a well-defined term. A reasonable person might assume this to be an element's `textContent` property, but many parsers (at least JS, PHP, and Go; not Python) interpret it as _trimmed_ `textContent`.

**Comment by gRegorLove** [comment]
I think this is being discussed in #20 and #15

**Comment by JKingweb** [comment]
Ah, I missed that. Thank you.
